### PR TITLE
Get sources from checkout and run Node.js test suite

### PR DESCRIPTION
**Pull request by Elexy**

### CODE REVIEW

**Comment by Elexy** [comment]
@mcollina @mavdi The release download we validated with a GPG key, now we 'just' clone. Wondering if we can / need to secure that in some way.

**Comment by mavdi** [comment]
Node tags in GitHub are signed. As long as we can trust the Github certificate, I don't think we need to further verify it.

**Comment by Elexy** [comment]
The Node.js tests are running in this branch and we are verifying the Tag with GPG keys.
https://circleci.com/gh/nearform/nodejs-distribution/1124

Anything else before approval?

**Comment by mavdi** [comment]
Looks good!

**Pull request merged**
